define('home.tpl', ['Handlebars','Handlebars.CompilerNameLookup'], function (Handlebars, compilerNameLookup){ var template = Handlebars.template({"1":function(container,depth0,helpers,partials,data,blockParams,depths) {
    return " <li><div class=\"home-slide-main-container\"><div class=\"home-slide-image-container\"><img src=\""
    + container.escapeExpression((compilerNameLookup(helpers,"resizeImage") || (depth0 && compilerNameLookup(depth0,"resizeImage")) || helpers.helperMissing).call(depth0 != null ? depth0 : (container.nullContext || {}),depth0,(depths[1] != null ? compilerNameLookup(depths[1],"imageHomeSize") : depths[1]),{"name":"resizeImage","hash":{},"data":data}))
    + "\" alt=\"\" /></div><div class=\"home-slide-caption\"><h2 class=\"home-slide-caption-title\">SAMPLE HEADLINE</h2><p>Example descriptive text displayed on multiple lines.</p><div class=\"home-slide-caption-button-container\"><a href=\"/search\" class=\"home-slide-caption-button\">Shop Now</a></div></div></div></li> ";
},"3":function(container,depth0,helpers,partials,data,blockParams,depths) {
    var alias1=depth0 != null ? depth0 : (container.nullContext || {}), alias2=helpers.helperMissing, alias3=container.escapeExpression;

  return " <li><div class=\"home-slide-main-container\"><div class=\"home-slide-image-container\"><img src=\""
    + alias3((compilerNameLookup(helpers,"getThemeAssetsPath") || (depth0 && compilerNameLookup(depth0,"getThemeAssetsPath")) || alias2).call(alias1,(compilerNameLookup(helpers,"resizeImage") || (depth0 && compilerNameLookup(depth0,"resizeImage")) || alias2).call(alias1,"img/carousel-home-1.png",(depths[1] != null ? compilerNameLookup(depths[1],"imageHomeSize") : depths[1]),{"name":"resizeImage","hash":{},"data":data}),{"name":"getThemeAssetsPath","hash":{},"data":data}))
    + "\" alt=\"\" /></div><div class=\"home-slide-caption\"><h2 class=\"home-slide-caption-title\">SAMPLE HEADLINE</h2><p>Example descriptive text displayed on multiple lines.</p><div class=\"home-slide-caption-button-container\"><a href=\"/search\" class=\"home-slide-caption-button\">Shop Now</a></div></div></div></li><li><div class=\"home-slide-main-container\"><div class=\"home-slide-image-container\"><img src=\""
    + alias3((compilerNameLookup(helpers,"getThemeAssetsPath") || (depth0 && compilerNameLookup(depth0,"getThemeAssetsPath")) || alias2).call(alias1,(compilerNameLookup(helpers,"resizeImage") || (depth0 && compilerNameLookup(depth0,"resizeImage")) || alias2).call(alias1,"img/carousel-home-2.png",(depths[1] != null ? compilerNameLookup(depths[1],"imageHomeSize") : depths[1]),{"name":"resizeImage","hash":{},"data":data}),{"name":"getThemeAssetsPath","hash":{},"data":data}))
    + "\" alt=\"\" /></div><div class=\"home-slide-caption\"><h2 class=\"home-slide-caption-title\">SAMPLE HEADLINE</h2><p>Example descriptive text displayed on multiple lines.</p><div class=\"home-slide-caption-button-container\"><a href=\"/search\" class=\"home-slide-caption-button\">Shop Now</a></div></div></div></li><li><div class=\"home-slide-main-container\"><div class=\"home-slide-image-container\"><img src=\""
    + alias3((compilerNameLookup(helpers,"getThemeAssetsPath") || (depth0 && compilerNameLookup(depth0,"getThemeAssetsPath")) || alias2).call(alias1,(compilerNameLookup(helpers,"resizeImage") || (depth0 && compilerNameLookup(depth0,"resizeImage")) || alias2).call(alias1,"img/carousel-home-3.png",(depths[1] != null ? compilerNameLookup(depths[1],"imageHomeSize") : depths[1]),{"name":"resizeImage","hash":{},"data":data}),{"name":"getThemeAssetsPath","hash":{},"data":data}))
    + "\" alt=\"\" /></div><div class=\"home-slide-caption\"><h2 class=\"home-slide-caption-title\">SAMPLE HEADLINE</h2><p>Example descriptive text displayed on multiple lines.</p><div class=\"home-slide-caption-button-container\"><a href=\"/search\" class=\"home-slide-caption-button\">Shop Now</a></div></div></div></li> ";
},"5":function(container,depth0,helpers,partials,data,blockParams,depths) {
    var helper, alias1=depth0 != null ? depth0 : (container.nullContext || {}), alias2=helpers.helperMissing, alias3=container.escapeExpression;

  return " <div class=\"home-banner-main-cell-nth"
    + alias3(((helper = (helper = compilerNameLookup(helpers,"index") || (data && compilerNameLookup(data,"index"))) != null ? helper : alias2),(typeof helper === "function" ? helper.call(alias1,{"name":"index","hash":{},"data":data}) : helper)))
    + "\"><div class=\"home-banner-main-cell-bg\"><img src=\""
    + alias3((compilerNameLookup(helpers,"resizeImage") || (depth0 && compilerNameLookup(depth0,"resizeImage")) || alias2).call(alias1,depth0,(depths[1] != null ? compilerNameLookup(depths[1],"imageHomeSizeBottom") : depths[1]),{"name":"resizeImage","hash":{},"data":data}))
    + "\" alt=\"\" ><div class=\"home-banner-main-cell-text\">EXAMPLE TEXT</div></div></div> ";
},"7":function(container,depth0,helpers,partials,data,blockParams,depths) {
    var alias1=depth0 != null ? depth0 : (container.nullContext || {}), alias2=helpers.helperMissing, alias3=container.escapeExpression;

  return " <div class=\"home-banner-main-cell-nth0\"><div class=\"home-banner-main-cell-bg\"><img src=\""
    + alias3((compilerNameLookup(helpers,"getThemeAssetsPath") || (depth0 && compilerNameLookup(depth0,"getThemeAssetsPath")) || alias2).call(alias1,(compilerNameLookup(helpers,"resizeImage") || (depth0 && compilerNameLookup(depth0,"resizeImage")) || alias2).call(alias1,"img/banner-bottom-home-1.jpg",(depths[1] != null ? compilerNameLookup(depths[1],"imageHomeSizeBottom") : depths[1]),{"name":"resizeImage","hash":{},"data":data}),{"name":"getThemeAssetsPath","hash":{},"data":data}))
    + "\" alt=\"\" ><div class=\"home-banner-main-cell-text\">EXAMPLE TEXT</div></div></div><div class=\"home-banner-main-cell-nth1\"><div class=\"home-banner-main-cell-bg\"><img src=\""
    + alias3((compilerNameLookup(helpers,"getThemeAssetsPath") || (depth0 && compilerNameLookup(depth0,"getThemeAssetsPath")) || alias2).call(alias1,(compilerNameLookup(helpers,"resizeImage") || (depth0 && compilerNameLookup(depth0,"resizeImage")) || alias2).call(alias1,"img/banner-bottom-home-2.jpg",(depths[1] != null ? compilerNameLookup(depths[1],"imageHomeSizeBottom") : depths[1]),{"name":"resizeImage","hash":{},"data":data}),{"name":"getThemeAssetsPath","hash":{},"data":data}))
    + "\" alt=\"\" ><div class=\"home-banner-main-cell-text\">EXAMPLE TEXT</div></div></div><div class=\"home-banner-main-cell-nth2\"><div class=\"home-banner-main-cell-bg\"><img src=\""
    + alias3((compilerNameLookup(helpers,"getThemeAssetsPath") || (depth0 && compilerNameLookup(depth0,"getThemeAssetsPath")) || alias2).call(alias1,(compilerNameLookup(helpers,"resizeImage") || (depth0 && compilerNameLookup(depth0,"resizeImage")) || alias2).call(alias1,"img/banner-bottom-home-3.jpg",(depths[1] != null ? compilerNameLookup(depths[1],"imageHomeSizeBottom") : depths[1]),{"name":"resizeImage","hash":{},"data":data}),{"name":"getThemeAssetsPath","hash":{},"data":data}))
    + "\" alt=\"\" ><div class=\"home-banner-main-cell-text\">EXAMPLE TEXT</div></div></div> ";
},"compiler":[7,">= 4.0.0"],"main":function(container,depth0,helpers,partials,data,blockParams,depths) {
    var stack1, alias1=depth0 != null ? depth0 : (container.nullContext || {});

  return " <div class=\"home\"><div class=\"home-banner-top\"><p class=\"home-banner-top-message\"> "
    + container.escapeExpression((compilerNameLookup(helpers,"translate") || (depth0 && compilerNameLookup(depth0,"translate")) || helpers.helperMissing).call(alias1,"Use promo code <strong>SCADEMO</strong> for <strong>30%</strong> off your purchase",{"name":"translate","hash":{},"data":data}))
    + " </p></div><div data-view=\"Hello.World\"></div><div class=\"home-slider-container\"><div class=\"home-image-slider\"><ul data-slider class=\"home-image-slider-list\"> "
    + ((stack1 = compilerNameLookup(helpers,"each").call(alias1,(depth0 != null ? compilerNameLookup(depth0,"carouselImages") : depth0),{"name":"each","hash":{},"fn":container.program(1, data, 0, blockParams, depths),"inverse":container.program(3, data, 0, blockParams, depths),"data":data})) != null ? stack1 : "")
    + " </ul></div></div><div class=\"home-banner-main\"> "
    + ((stack1 = compilerNameLookup(helpers,"each").call(alias1,(depth0 != null ? compilerNameLookup(depth0,"bottomBannerImages") : depth0),{"name":"each","hash":{},"fn":container.program(5, data, 0, blockParams, depths),"inverse":container.program(7, data, 0, blockParams, depths),"data":data})) != null ? stack1 : "")
    + " </div><div class=\"home-merchandizing-zone\"><div data-id=\"your-merchandising-zone\" data-type=\"merchandising-zone\"></div></div></div>  ";
},"useData":true,"useDepths":true}); template.Name = 'home'; return template;});