define('login_register_reset_password.tpl', ['Handlebars','Handlebars.CompilerNameLookup'], function (Handlebars, compilerNameLookup){ var template = Handlebars.template({"compiler":[7,">= 4.0.0"],"main":function(container,depth0,helpers,partials,data) {
    var alias1=depth0 != null ? depth0 : (container.nullContext || {}), alias2=helpers.helperMissing, alias3=container.escapeExpression;

  return " <div class=\"login-register-reset-password-body\"><h2 class=\"login-register-reset-password-title\"> "
    + alias3((compilerNameLookup(helpers,"translate") || (depth0 && compilerNameLookup(depth0,"translate")) || alias2).call(alias1,"Reset Password",{"name":"translate","hash":{},"data":data}))
    + " </h2><form class=\"login-register-reset-password-form\" novalidate><p class=\"login-register-reset-password-description\"> "
    + alias3((compilerNameLookup(helpers,"translate") || (depth0 && compilerNameLookup(depth0,"translate")) || alias2).call(alias1,"Enter a new password below",{"name":"translate","hash":{},"data":data}))
    + " </p><fieldset><div class=\"login-register-reset-password-control-group\" data-validation=\"control-group\"><label class=\"login-register-reset-password-control-label\" for=\"password\"> "
    + alias3((compilerNameLookup(helpers,"translate") || (depth0 && compilerNameLookup(depth0,"translate")) || alias2).call(alias1,"Password <small class=\"login-register-reset-password-forgot-password-form-required\">*</small>",{"name":"translate","hash":{},"data":data}))
    + " </label><div class=\"login-register-reset-password-controls\" data-validation=\"control\"><input type=\"password\" class=\"login-register-reset-password-input\" id=\"password\" name=\"password\" value=\"\"></div></div><div class=\"login-register-reset-password-control-group\" data-validation=\"control-group\"><label class=\"login-register-reset-password-control-label\" for=\"confirm_password\">"
    + alias3((compilerNameLookup(helpers,"translate") || (depth0 && compilerNameLookup(depth0,"translate")) || alias2).call(alias1,"Confirm Password <small class=\"login-register-reset-password-forgot-password-form-required\">*</small>",{"name":"translate","hash":{},"data":data}))
    + "</label><div class=\"login-register-reset-password-controls\" data-validation=\"control\"><input type=\"password\" class=\"login-register-reset-password-input\" id=\"confirm_password\" name=\"confirm_password\" value=\"\"></div></div><div data-type=\"alert-placeholder\"></div><div class=\"login-register-reset-password-control-group\"><button type=\"submit\" class=\"login-register-reset-password-submit\">"
    + alias3((compilerNameLookup(helpers,"translate") || (depth0 && compilerNameLookup(depth0,"translate")) || alias2).call(alias1,"Change Password",{"name":"translate","hash":{},"data":data}))
    + "</button><a class=\"login-register-reset-password-sign-in\" href=\"/login-register\" data-target=\".register\">"
    + alias3((compilerNameLookup(helpers,"translate") || (depth0 && compilerNameLookup(depth0,"translate")) || alias2).call(alias1,"Cancel & Return To Log in",{"name":"translate","hash":{},"data":data}))
    + "</a></div></fieldset></form></div>  ";
},"useData":true}); template.Name = 'login_register_reset_password'; return template;});