define('product_reviews_form_preview.tpl', ['Handlebars','Handlebars.CompilerNameLookup','facets_item_cell_list.tpl'], function (Handlebars, compilerNameLookup){ var template = Handlebars.template({"compiler":[7,">= 4.0.0"],"main":function(container,depth0,helpers,partials,data) {
    var stack1, helper, alias1=depth0 != null ? depth0 : (container.nullContext || {}), alias2=helpers.helperMissing, alias3=container.escapeExpression;

  return " <div class=\"product-reviews-form-preview\"><h1>"
    + ((stack1 = ((helper = (helper = compilerNameLookup(helpers,"header") || (depth0 != null ? compilerNameLookup(depth0,"header") : depth0)) != null ? helper : alias2),(typeof helper === "function" ? helper.call(alias1,{"name":"header","hash":{},"data":data}) : helper))) != null ? stack1 : "")
    + "</h1><div class=\"product-reviews-form-preview-divider-desktop\"></div><div class=\"product-reviews-form-preview-divider\"></div><div class=\"product-reviews-form-preview-item-cell\"><div data-view=\"Facets.ItemCell\" data-template=\"facets_item_cell_list\"></div></div><div class=\"product-reviews-form-preview-content\"><form><div class=\"product-reviews-form-preview-main\"><div data-view=\"ProductReviews.Preview\"></div></div><div class=\"product-reviews-form-preview-actions\"><button type=\"button\" class=\"product-reviews-form-preview-actions-button-submit\" data-action=\"save\">"
    + alias3((compilerNameLookup(helpers,"translate") || (depth0 && compilerNameLookup(depth0,"translate")) || alias2).call(alias1,"Submit Review",{"name":"translate","hash":{},"data":data}))
    + "</button><button type=\"button\" class=\"product-reviews-form-preview-actions-button-edit\" data-action=\"edit\">"
    + alias3((compilerNameLookup(helpers,"translate") || (depth0 && compilerNameLookup(depth0,"translate")) || alias2).call(alias1,"Edit Review",{"name":"translate","hash":{},"data":data}))
    + "</button></div></form></div></div>  ";
},"useData":true}); template.Name = 'product_reviews_form_preview'; return template;});