define('profile_change_email.tpl', ['Handlebars','Handlebars.CompilerNameLookup'], function (Handlebars, compilerNameLookup){ var template = Handlebars.template({"compiler":[7,">= 4.0.0"],"main":function(container,depth0,helpers,partials,data) {
    var alias1=depth0 != null ? depth0 : (container.nullContext || {}), alias2=helpers.helperMissing, alias3=container.escapeExpression;

  return " <section class=\"profile-change-email\"><div data-type=\"alert-placeholder\"></div><div class=\"profile-change-email-form-area\"><form class=\"profile-change-email-form\"><fieldset><small class=\"profile-change-email-form-label\">"
    + alias3((compilerNameLookup(helpers,"translate") || (depth0 && compilerNameLookup(depth0,"translate")) || alias2).call(alias1,"Required",{"name":"translate","hash":{},"data":data}))
    + " <span class=\"profile-change-email-form-group-label-required\">*</span></small><div class=\"profile-change-email-form-group\" data-input=\"new_email\" data-validation=\"control-group\"><label class=\"profile-change-email-form-group-label\" for=\"new_email\">"
    + alias3((compilerNameLookup(helpers,"translate") || (depth0 && compilerNameLookup(depth0,"translate")) || alias2).call(alias1,"New Email",{"name":"translate","hash":{},"data":data}))
    + " <span class=\"profile-change-email-form-group-label-required\">*</span></label><div  class=\"profile-change-email-group-form-controls\" data-validation=\"control\"><input type=\"email\" class=\"profile-change-email-form-group-input\" id=\"new_email\" name=\"new_email\" value=\"\" placeholder=\""
    + alias3((compilerNameLookup(helpers,"translate") || (depth0 && compilerNameLookup(depth0,"translate")) || alias2).call(alias1,"your@email.com",{"name":"translate","hash":{},"data":data}))
    + "\"></div></div><div class=\"profile-change-email-form-group\" data-input=\"confirm_email\" data-validation=\"control-group\"><label class=\"profile-change-email-form-group-label\" for=\"confirm_email\">"
    + alias3((compilerNameLookup(helpers,"translate") || (depth0 && compilerNameLookup(depth0,"translate")) || alias2).call(alias1,"Confirm New Email",{"name":"translate","hash":{},"data":data}))
    + " <span class=\"profile-change-email-form-group-label-required\">*</span></label><div  class=\"profile-change-email-group-form-controls\" data-validation=\"control\"><input type=\"email\" class=\"profile-change-email-form-group-input\" id=\"confirm_email\" name=\"confirm_email\" value=\"\" placeholder=\""
    + alias3((compilerNameLookup(helpers,"translate") || (depth0 && compilerNameLookup(depth0,"translate")) || alias2).call(alias1,"your@email.com",{"name":"translate","hash":{},"data":data}))
    + "\"></div></div><div class=\"profile-change-email-form-group\" data-input=\"current_email\" data-validation=\"control-group\"><label class=\"profile-change-email-form-group-label\" for=\"current_password\">"
    + alias3((compilerNameLookup(helpers,"translate") || (depth0 && compilerNameLookup(depth0,"translate")) || alias2).call(alias1,"Password",{"name":"translate","hash":{},"data":data}))
    + " <span class=\"profile-change-email-form-group-label-required\">*</span></label><div  class=\"profile-change-email-group-form-controls\" data-validation=\"control\"><input type=\"password\" class=\"profile-change-email-form-group-input\" id=\"current_password\" name=\"current_password\" value=\"\"></div></div></fieldset><p class=\"profile-change-email-form-info-block\"><small> "
    + alias3((compilerNameLookup(helpers,"translate") || (depth0 && compilerNameLookup(depth0,"translate")) || alias2).call(alias1,"You will still be able to login with your current email address and password until your new email address is verified.",{"name":"translate","hash":{},"data":data}))
    + " </small></p><div class=\"profile-change-email-form-actions\"><button type=\"submit\" class=\"profile-change-email-form-actions-change\">"
    + alias3((compilerNameLookup(helpers,"translate") || (depth0 && compilerNameLookup(depth0,"translate")) || alias2).call(alias1,"Send Verification Email",{"name":"translate","hash":{},"data":data}))
    + "</button></div></form></div></section>";
},"useData":true}); template.Name = 'profile_change_email'; return template;});