define('quick_add.tpl', ['Handlebars','Handlebars.CompilerNameLookup'], function (Handlebars, compilerNameLookup){ var template = Handlebars.template({"compiler":[7,">= 4.0.0"],"main":function(container,depth0,helpers,partials,data) {
    var helper, alias1=depth0 != null ? depth0 : (container.nullContext || {}), alias2=helpers.helperMissing, alias3="function", alias4=container.escapeExpression;

  return " <div class=\"quick-add-box\"><form novalidate action=\"#\"><div class=\"quick-add-box-left\" data-input=\"quickaddSearch\" data-validation=\"control-group\"><label for=\"quickaddSearch\">"
    + alias4(((helper = (helper = compilerNameLookup(helpers,"itemTitle") || (depth0 != null ? compilerNameLookup(depth0,"itemTitle") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"itemTitle","hash":{},"data":data}) : helper)))
    + "</label><div class=\"quick-add-box-input\" data-validation=\"control\"><div class=\"quick-add-box-input-search\" data-view=\"ItemsSearcher\"></div><a class=\"quick-add-box-input-search-reset\" data-type=\"quick-add-reset\"><i class=\"quick-add-box-input-search-reset-icon\"></i></a></div></div><div class=\"quick-add-box-right\" data-input=\"quickaddSearch\" data-validation=\"control-group\"><label for=\"quantity\" class=\"quick-add-input-quantity\">"
    + alias4(((helper = (helper = compilerNameLookup(helpers,"quantityTitle") || (depth0 != null ? compilerNameLookup(depth0,"quantityTitle") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"quantityTitle","hash":{},"data":data}) : helper)))
    + "</label><div class=\"quick-add-box-right-main\"><div class=\"quick-add-box-right-input\" data-validation=\"control\"><div class=\"quick-add-box-right-actionable-input-qty\"><button type=\"button\" class=\"quick-add-box-right-quantity-remove\" data-action=\"minus\">-</button><input data-type=\"quantity-input\" type=\"number\" name=\"quantity\" id=\"quantity\" class=\"quick-add-box-right-quantity-value\" min=\"1\"><button type=\"button\" class=\"quick-add-box-right-quantity-add\" data-action=\"plus\">+</button></div><small class=\"quick-add-box-minimum-top\" data-type=\"minimum-quantity\"></small></div><button class=\"quick-add-box-button\" type=\"submit\">"
    + alias4((compilerNameLookup(helpers,"translate") || (depth0 && compilerNameLookup(depth0,"translate")) || alias2).call(alias1,"Add Item",{"name":"translate","hash":{},"data":data}))
    + "</button><small class=\"quick-add-box-minimum-bottom\" data-type=\"minimum-quantity\"></small></div></div></form></div>  ";
},"useData":true}); template.Name = 'quick_add'; return template;});